#!mast -x Syckfile -x PROFILE .ruby bin lib man spec test [A-Z]*
.ruby/date
.ruby/loadpath
.ruby/name
.ruby/version
lib/plugin.rb
test/demos/helper.rb
test/demos/plugins/example.rb
test/demos/usage.rdoc
README.rdoc
HISTORY
VERSION
COPYING
